# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Robin Finesilver - Piano For Hire
email: rfinesilver@hotmail.com description: > # this means to ignore newlines until "baseurl:"
  I'm trying to build a quick website so that I can put gig lists in and I'm not on BLOODY FACEBOOK!
baseurl: "https://robinfinesilver.github.io/" # the subpath of your site, e.g. /blog
url: "https://www.facebook.com/robin.finesilver.music/" # the base hostname & protocol for your site
twitter_username: @RobinFinesilver
github_username:  RobinFinesilver

# Build settings
markdown: kramdown
